# Generated by Django 5.1.6 on 2025-03-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_name_enrollment_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_of_birth',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
