# Generated by Django 5.1.6 on 2025-03-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_enrollment_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_of_birth',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
