# Generated by Django 5.1.6 on 2025-03-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_enrollment_delete_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='age',
            field=models.IntegerField(),
        ),
    ]
