# Generated by Django 5.1.6 on 2025-03-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_enrollment_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='age',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
    ]
